# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a7b855af45204abd3fe941670a66305f741e9de0f0a99d1b059b320cc3c3b964b27dc36a0aea7f55e5cff4877a4f09aa9ead05f13f269e9db236a0c32899552

test:
  secret_key_base: da2af0f7a685444c995d4e9cda1b1695ee13ef4e61d69e57798991ff86f2c468241876b22891d8845124ef12ee7f37cedccdbf1742446590a653031d213db003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
